#run oc process -f bc.yaml -p NAME=tbtb-yeaf IMAGE_TAG=latest OC_REPO_SECRET_USER=user-at-github | oc apply -f -
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${NAME}
  labels:
    buildconfig: ${NAME}
objects:
  - apiVersion: v1
    kind: BuildConfig
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${IMAGE_TAG}
      postCommit: {}
      resources:
        requests:
          cpu: 2
          memory: 8Gi
        limits:
          cpu: 4
          memory: 16Gi
      runPolicy: Serial
      source:
        git:
          ref: ${REPO_BRANCH}
          uri: ${REPO_NAME}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: ./Dockerfile
          env:
            - name: "TEST_ARG"
              value: "hi there"
            - name: USER_ID
              value: ${OC_USER_ID}
            - name: ENV_ARG
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: ".env"
            - name: ENV_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-connection"
            - name: ENV_DB_HOST
              value: ${NAME}-patroni-master
            - name: ENV_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-port"
            - name: ENV_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-name"
            - name: ENV_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-username"
            - name: ENV_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-password"
            - name: ENV_DB_PREFIX
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "database-prefix"
            - name: ENV_DEFAULT_CONF
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${REPO_BRANCH}
                  key: "000-default-conf"
        type: Docker
      successfulBuildsHistoryLimit: 5
    metadata:
      generation: 2
      labels:
        build: ${NAME}
        buildconfig: ${NAME}
        build-branch: ${REPO_BRANCH}
      name: ${NAME}
      namespace: ${BUILD_NAMESPACE}
  - apiVersion: v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      generation: 1
      labels:
        build: ${NAME}
        buildconfig: ${NAME}
        build-branch: ${REPO_BRANCH}
        image-stream: ${NAME}
        image-stream-tag: ${IMAGE_TAG}
      name: ${NAME}
parameters:
  - name: NAME
    required: true
    description: some desc for this component
  - name: BUILD_NAMESPACE
    required: true
    description: some desc for this component
  - name: IMAGE_TAG
    required: true
    description: some line to describe the image_tag_x parameter
  - name: REPO_NAME
    required: true
    description: some line to describe the image_tag_x parameter
  - name: REPO_BRANCH
    required: true
    description: some line to describe the image_tag_x parameter
  - name: OC_USER_ID
    required: true
    description: openshift env default user_id

  - name: LABEL_NAME
    required: false
#  - name: IMAGE_TAG
#    required: false
  - name: NAMESPACE
    required: false

  - name: CPU_REQUESTS
    required: true
  - name: CPU_LIMITS
    required: true
  - name: MEM_REQUESTS
    required: true
  - name: MEM_LIMITS
    required: true
  - name: MIN_REPLICAS
    required: true
  - name: MAX_REPLICAS
    required: true
